"""V3.1.1 — Excel import layer tests.

Covers:

* :mod:`workbook_detector` — file-type detection across the 8
  supported types plus the ``unknown`` fallback; filename vs header
  vs sheet-name vs data spot-check signals and their consistency.
* :mod:`column_aliases` — header normalisation, alias matching,
  fuzzy fallback, required / optional missing reporting, unmapped
  columns kept (never silently dropped).
* :mod:`product_loader`, :mod:`search_loader`, :mod:`keyword_loader`,
  :mod:`market_loader`, :mod:`category_loader`,
  :mod:`brand_analytics_loader`, :mod:`brand_loader`,
  :mod:`seller_loader` — typed record construction, source
  traceability, blank-row skipping, header-variant tolerance.
* :mod:`normalized_models` — :meth:`AmazonProduct.dedup_key` and
  friends (full ASIN dedup lives in V3.1.2; here we only assert the
  synthetic key is correct).
* Search-appearance multiplicity — same (keyword, ASIN) appearing
  under multiple placements / pages is preserved, not deduped.

Tests are stdlib-only (``unittest``). Fixtures live under
``tests/fixtures/`` and are regenerated by
``tests/fixtures/_generate_amazon_xlsx_fixtures.py``.
"""

from __future__ import annotations

import os
import unittest
from decimal import Decimal
from typing import Any, List

from src.modules.amazon.importers import (
    AmazonProduct,
    AmazonSearchAppearance,
    BrandMetric,
    CategoryMetric,
    ColumnMappingResult,
    KeywordMetric,
    SellerMetric,
    SheetInfo,
    SourceInfo,
    SUPPORTED_TYPES,
    WorkbookDetectionResult,
    brand_analytics_loader,
    brand_loader,
    build_column_mapping,
    category_loader,
    detect_workbook,
    get_loader,
    keyword_loader,
    market_loader,
    normalize_header,
    product_loader,
    search_loader,
    seller_loader,
)
from src.modules.amazon.importers.column_aliases import (
    OPTIONAL_FIELDS_BY_TYPE,
    REQUIRED_FIELDS_BY_TYPE,
    STANDARD_FIELDS,
    _fuzzy_similarity,
)

FIXTURE_DIR = os.path.join("tests", "fixtures")


def _fixture(name: str) -> str:
    return os.path.join(FIXTURE_DIR, name)


class TestColumnAliases(unittest.TestCase):
    """Header normalisation and field-mapping behaviour."""

    def test_normalize_header_strips_units_and_whitespace(self) -> None:
        self.assertEqual(normalize_header("FBA($)"), "fba")
        self.assertEqual(normalize_header("Monthly  Sales"), "monthlysales")
        self.assertEqual(normalize_header("月 销\n量"), "月销量")
        self.assertEqual(normalize_header("FBA Fee (USD)"), "fbafee")
        self.assertEqual(normalize_header("  Rating(%)  "), "rating")
        self.assertEqual(normalize_header(""), "")
        self.assertEqual(normalize_header(None), "")  # type: ignore[arg-type]

    def test_normalize_header_drops_parenthesised_units(self) -> None:
        # ``(lbs)``, ``(cm)``, ``(in)`` etc. are stripped wholesale.
        self.assertEqual(normalize_header("Weight(lbs)"), "weight")
        self.assertEqual(normalize_header("Dimensions(cm)"), "dimensions")
        self.assertEqual(normalize_header("月销量（近30天）"), "月销量")

    def test_standard_fields_includes_canonical_name_as_first_alias(self) -> None:
        for std_field, aliases in STANDARD_FIELDS.items():
            self.assertEqual(aliases[0], std_field,
                             f"{std_field} must list itself first")

    def test_required_and_optional_keys_match_supported_types(self) -> None:
        for ftype in REQUIRED_FIELDS_BY_TYPE:
            self.assertIn(ftype, SUPPORTED_TYPES)
        for ftype in OPTIONAL_FIELDS_BY_TYPE:
            self.assertIn(ftype, SUPPORTED_TYPES)

    def test_build_column_mapping_exact_match(self) -> None:
        headers = ["ASIN", "Title", "Price", "Brand"]
        result = build_column_mapping(headers, "products")
        self.assertIsInstance(result, ColumnMappingResult)
        fields = {m.standard_field for m in result.mappings}
        self.assertIn("asin", fields)
        self.assertIn("title", fields)
        self.assertIn("price", fields)
        self.assertIn("brand", fields)
        for m in result.mappings:
            self.assertEqual(m.mapping_method, "exact")
            self.assertEqual(m.confidence, "high")

    def test_build_column_mapping_chinese_aliases(self) -> None:
        headers = ["商品ASIN", "商品标题", "售价", "品牌", "月销量", "评分数"]
        result = build_column_mapping(headers, "products")
        field_to_header = result.field_to_column
        self.assertIn("asin", field_to_header)
        self.assertIn("title", field_to_header)
        self.assertIn("price", field_to_header)
        self.assertIn("brand", field_to_header)
        self.assertIn("monthly_sales", field_to_header)
        self.assertIn("review_count", field_to_header)
        for m in result.mappings:
            self.assertEqual(m.mapping_method, "alias")
            self.assertEqual(m.confidence, "high")

    def test_build_column_mapping_handles_synonyms(self) -> None:
        # Multiple synonyms for monthly_sales.
        for raw in ("月销量", "近30天销量", "Monthly Sales", "Sales per Month", "30天销量", "月销"):
            result = build_column_mapping([raw], "products")
            self.assertIn("monthly_sales", result.field_to_column,
                          f"failed for synonym: {raw}")

    def test_build_column_mapping_unit_suffix_tolerance(self) -> None:
        # The same logical field with different unit suffixes should
        # collapse to the same standard field.
        for raw in ("FBA($)", "FBA费用", "FBA Fee", "Fulfillment Fee"):
            result = build_column_mapping([raw], "products")
            self.assertIn("fba_fee", result.field_to_column,
                          f"failed for variant: {raw}")

    def test_build_column_mapping_handles_whitespace_and_case(self) -> None:
        headers = ["  asin  ", "TITLE", "Price", "  Brand "]
        result = build_column_mapping(headers, "products")
        self.assertEqual(len(result.mappings), 4)
        self.assertEqual(set(result.field_to_column.keys()),
                         {"asin", "title", "price", "brand"})

    def test_build_column_mapping_reorders_columns(self) -> None:
        # Column ORDER must not matter — the loader resolves by name.
        forward = ["ASIN", "Title", "Price"]
        reverse = ["Price", "Title", "ASIN"]
        r1 = build_column_mapping(forward, "products")
        r2 = build_column_mapping(reverse, "products")
        self.assertEqual(set(r1.field_to_column.keys()),
                         set(r2.field_to_column.keys()))

    def test_unmapped_columns_kept_not_dropped(self) -> None:
        headers = ["ASIN", "Title", "Price", "Mystery Column", "Another Unknown"]
        result = build_column_mapping(headers, "products")
        self.assertIn("Mystery Column", result.unmapped_columns)
        self.assertIn("Another Unknown", result.unmapped_columns)
        self.assertEqual(len(result.unmapped_columns), 2)
        # Mapping warnings should mention the unmapped columns.
        self.assertTrue(any("unmapped" in w.lower() for w in result.mapping_warnings))

    def test_required_missing_reported(self) -> None:
        # Products requires asin/title/price — drop "price".
        result = build_column_mapping(["ASIN", "Title"], "products")
        self.assertIn("price", result.required_missing)
        self.assertTrue(any("required" in w.lower() for w in result.mapping_warnings))

    def test_optional_missing_reported(self) -> None:
        # Provide the bare required set only — every optional field
        # should appear in optional_missing.
        result = build_column_mapping(["ASIN", "Title", "Price"], "products")
        self.assertIn("brand", result.optional_missing)
        self.assertIn("monthly_sales", result.optional_missing)
        self.assertIn("fba_fee", result.optional_missing)

    def test_duplicate_headers_flagged(self) -> None:
        result = build_column_mapping(["ASIN", "ASIN", "Title"], "products")
        # Only one mapping is produced; the duplicate is flagged.
        asin_mappings = [m for m in result.mappings if m.standard_field == "asin"]
        self.assertEqual(len(asin_mappings), 1)
        self.assertTrue(any("duplicate" in w.lower() for w in result.mapping_warnings))

    def test_fuzzy_similarity_thresholds(self) -> None:
        # Identical strings -> 1.0.
        self.assertEqual(_fuzzy_similarity("asin", "asin"), 1.0)
        # Empty -> 0.
        self.assertEqual(_fuzzy_similarity("", "asin"), 0.0)
        # Short non-matching strings -> 0.
        self.assertEqual(_fuzzy_similarity("abc", "xyz"), 0.0)
        # Substring fallback for very short tokens.
        self.assertGreater(_fuzzy_similarity("ab", "abc"), 0.0)

    def test_fuzzy_match_emits_low_confidence(self) -> None:
        # "Tittle" is one char off "Title" — trigram similarity should
        # exceed the threshold and produce a low-confidence fuzzy match.
        result = build_column_mapping(["ASIN", "Tittle", "Price"], "products")
        title_mapping = [m for m in result.mappings if m.standard_field == "title"]
        if title_mapping:  # fuzzy may or may not fire depending on threshold
            self.assertEqual(title_mapping[0].mapping_method, "fuzzy")
            self.assertEqual(title_mapping[0].confidence, "low")


class TestWorkbookDetector(unittest.TestCase):
    """File-type detection across all 8 supported types."""

    def test_supported_types_complete(self) -> None:
        expected = {"products", "search", "keyword", "market", "category",
                    "brand_analytics", "brands", "sellers", "unknown"}
        self.assertEqual(set(SUPPORTED_TYPES), expected)

    def test_detect_products_file(self) -> None:
        r = detect_workbook(_fixture("products.xlsx"))
        self.assertEqual(r.detected_type, "products")
        self.assertEqual(r.confidence, "high")
        self.assertTrue(r.sheets)
        self.assertIsInstance(r.sheets[0], SheetInfo)

    def test_detect_search_file(self) -> None:
        r = detect_workbook(_fixture("search.xlsx"))
        self.assertEqual(r.detected_type, "search")
        self.assertEqual(r.confidence, "high")

    def test_detect_keyword_file(self) -> None:
        r = detect_workbook(_fixture("keyword_analysis.xlsx"))
        self.assertEqual(r.detected_type, "keyword")
        self.assertEqual(r.confidence, "high")

    def test_detect_market_file(self) -> None:
        r = detect_workbook(_fixture("market_analysis.xlsx"))
        self.assertEqual(r.detected_type, "market")
        self.assertEqual(r.confidence, "high")

    def test_detect_category_file(self) -> None:
        r = detect_workbook(_fixture("category_analysis.xlsx"))
        self.assertEqual(r.detected_type, "category")
        self.assertEqual(r.confidence, "high")

    def test_detect_brand_analytics_file(self) -> None:
        r = detect_workbook(_fixture("brand_analytics.xlsx"))
        self.assertEqual(r.detected_type, "brand_analytics")
        self.assertEqual(r.confidence, "high")
        # BA-only signature fields (click_share / conversion_share)
        # must be in recognized_columns.
        self.assertIn("click_share", r.recognized_columns)
        self.assertIn("conversion_share", r.recognized_columns)

    def test_detect_brands_file(self) -> None:
        r = detect_workbook(_fixture("brands.xlsx"))
        self.assertEqual(r.detected_type, "brands")

    def test_detect_sellers_file(self) -> None:
        r = detect_workbook(_fixture("sellers.xlsx"))
        self.assertEqual(r.detected_type, "sellers")
        self.assertEqual(r.confidence, "high")

    def test_detect_unknown_file(self) -> None:
        r = detect_workbook(_fixture("unknown_type.xlsx"))
        self.assertEqual(r.detected_type, "unknown")
        self.assertEqual(r.confidence, "low")

    def test_detect_missing_file_returns_unknown(self) -> None:
        r = detect_workbook("nonexistent.xlsx")
        self.assertEqual(r.detected_type, "unknown")
        self.assertEqual(r.confidence, "low")
        self.assertTrue(any("not found" in w.lower() for w in r.warnings))

    def test_detect_chinese_headers_products(self) -> None:
        r = detect_workbook(_fixture("products_chinese_headers.xlsx"))
        self.assertEqual(r.detected_type, "products")
        self.assertEqual(r.confidence, "high")

    def test_detect_reordered_columns_products(self) -> None:
        r = detect_workbook(_fixture("products_reordered.xlsx"))
        self.assertEqual(r.detected_type, "products")

    def test_detect_unknown_columns_products(self) -> None:
        r = detect_workbook(_fixture("products_unknown_columns.xlsx"))
        self.assertEqual(r.detected_type, "products")
        # Unknown columns must be retained, not silently dropped.
        self.assertTrue(r.unmapped_columns)

    def test_detect_missing_optional_products(self) -> None:
        r = detect_workbook(_fixture("products_missing_optional.xlsx"))
        self.assertEqual(r.detected_type, "products")

    def test_detect_missing_required_products_is_low_confidence(self) -> None:
        r = detect_workbook(_fixture("products_missing_required.xlsx"))
        # Even if filename hints "products", missing required fields
        # should keep the confidence below "high".
        self.assertIn(r.detected_type, ("products", "unknown"))
        self.assertNotEqual(r.confidence, "high")

    def test_detection_to_dict_round_trip(self) -> None:
        r = detect_workbook(_fixture("products.xlsx"))
        d = r.to_dict()
        self.assertEqual(d["detected_type"], r.detected_type)
        self.assertEqual(d["confidence"], r.confidence)
        self.assertEqual(len(d["sheets"]), len(r.sheets))
        self.assertIsInstance(d["sheets"][0], dict)

    def test_detection_records_reasons(self) -> None:
        r = detect_workbook(_fixture("products.xlsx"))
        self.assertTrue(r.detection_reasons)
        # Each reason should reference filename / sheet / data / header.
        joined = " ".join(r.detection_reasons).lower()
        self.assertTrue("filename" in joined or "header" in joined)

    def test_get_loader_dispatch(self) -> None:
        self.assertIs(get_loader("products"), product_loader)
        self.assertIs(get_loader("search"), search_loader)
        self.assertIs(get_loader("keyword"), keyword_loader)
        self.assertIs(get_loader("market"), market_loader)
        self.assertIs(get_loader("category"), category_loader)
        self.assertIs(get_loader("brand_analytics"), brand_analytics_loader)
        self.assertIs(get_loader("brands"), brand_loader)
        self.assertIs(get_loader("sellers"), seller_loader)
        self.assertIsNone(get_loader("unknown"))
        self.assertIsNone(get_loader("not_a_real_type"))


class TestProductLoader(unittest.TestCase):
    """Products loader — typed records, source traceability."""

    def test_load_products_returns_records(self) -> None:
        r = product_loader.load(_fixture("products.xlsx"))
        self.assertEqual(r.row_count, 3)
        self.assertEqual(len(r.records), 3)
        self.assertEqual(r.errors, [])
        for rec in r.records:
            self.assertIsInstance(rec, AmazonProduct)
            self.assertEqual(rec.source_type, "imported_excel")
            self.assertTrue(rec.source_file)
            self.assertTrue(rec.source_sheet)
            self.assertGreaterEqual(rec.source_row, 2)
            self.assertTrue(rec.source_hash)

    def test_load_products_field_values(self) -> None:
        r = product_loader.load(_fixture("products.xlsx"))
        first = r.records[0]
        self.assertTrue(first.asin.startswith("B0"))
        self.assertTrue(first.title)
        self.assertIsInstance(first.price, Decimal)
        self.assertGreater(first.price, Decimal("0"))

    def test_load_products_source_row_indices_are_correct(self) -> None:
        r = product_loader.load(_fixture("products.xlsx"))
        # Row 1 is the header; first data row is row 2.
        rows = [rec.source_row for rec in r.records]
        self.assertEqual(rows, sorted(rows))
        self.assertGreaterEqual(rows[0], 2)

    def test_load_products_to_dict_round_trip(self) -> None:
        r = product_loader.load(_fixture("products.xlsx"))
        d = r.records[0].to_dict()
        self.assertIn("asin", d)
        self.assertIn("source_file", d)
        self.assertIn("source_row", d)
        self.assertEqual(d["source_type"], "imported_excel")

    def test_load_products_missing_required_returns_warnings(self) -> None:
        r = product_loader.load(_fixture("products_missing_required.xlsx"))
        # Missing required should be reported either as warnings or errors.
        self.assertTrue(r.warnings or r.errors)

    def test_load_products_missing_optional_still_loads(self) -> None:
        r = product_loader.load(_fixture("products_missing_optional.xlsx"))
        self.assertGreater(r.row_count, 0)

    def test_load_products_chinese_headers(self) -> None:
        r = product_loader.load(_fixture("products_chinese_headers.xlsx"))
        self.assertGreater(r.row_count, 0)
        for rec in r.records:
            self.assertTrue(rec.asin or rec.title or rec.brand)

    def test_load_products_reordered_columns(self) -> None:
        r = product_loader.load(_fixture("products_reordered.xlsx"))
        self.assertGreater(r.row_count, 0)
        # Field values must be correct regardless of column order.
        first = r.records[0]
        self.assertTrue(first.asin)

    def test_load_products_unknown_columns_kept(self) -> None:
        r = product_loader.load(_fixture("products_unknown_columns.xlsx"))
        self.assertGreater(r.row_count, 0)
        # Unknown columns surface in unmapped_columns of column_mapping.
        assert r.column_mapping is not None
        self.assertTrue(r.column_mapping.unmapped_columns)

    def test_load_products_missing_file_errors(self) -> None:
        r = product_loader.load("does_not_exist.xlsx")
        self.assertEqual(r.row_count, 0)
        self.assertTrue(r.errors)

    def test_load_products_to_dict_includes_column_mapping(self) -> None:
        r = product_loader.load(_fixture("products.xlsx"))
        d = r.to_dict()
        self.assertIn("column_mapping", d)
        self.assertEqual(d["row_count"], 3)


class TestSearchLoader(unittest.TestCase):
    """Search-appearance loader — multiplicity preserved."""

    def test_load_search_returns_appearances(self) -> None:
        r = search_loader.load(_fixture("search.xlsx"))
        self.assertGreater(r.row_count, 0)
        for rec in r.records:
            self.assertIsInstance(rec, AmazonSearchAppearance)
            self.assertTrue(rec.keyword)
            self.assertTrue(rec.asin)

    def test_search_appearances_not_deduped(self) -> None:
        # Same ASIN appearing multiple times under the same keyword
        # (e.g. once sponsored, once organic, on different pages) must
        # produce multiple records — the loader must NOT dedup.
        r = search_loader.load(_fixture("search.xlsx"))
        keys = [(rec.keyword, rec.asin) for rec in r.records]
        unique_keys = set(keys)
        # If all fixtures happen to be unique, this still passes; the
        # assertion that matters is "records count == keys count"
        # (no silent dedup).
        self.assertEqual(len(keys), len(r.records))
        # Sanity: if there are duplicates, they are preserved.
        if len(keys) != len(unique_keys):
            self.assertGreater(len(r.records), len(unique_keys))

    def test_search_placement_type_normalisation(self) -> None:
        r = search_loader.load(_fixture("search.xlsx"))
        valid = {"sponsored", "organic", "unknown"}
        for rec in r.records:
            self.assertIn(rec.placement_type, valid)

    def test_search_sponsored_and_organic_flags_independent(self) -> None:
        # is_sponsored and is_organic are independent booleans.
        r = search_loader.load(_fixture("search.xlsx"))
        for rec in r.records:
            self.assertIsInstance(rec.is_sponsored, bool)
            self.assertIsInstance(rec.is_organic, bool)

    def test_search_source_traceability(self) -> None:
        r = search_loader.load(_fixture("search.xlsx"))
        for rec in r.records:
            self.assertEqual(rec.source_type, "imported_excel")
            self.assertTrue(rec.source_file)
            self.assertTrue(rec.source_sheet)
            self.assertGreaterEqual(rec.source_row, 2)


class TestKeywordLoader(unittest.TestCase):
    def test_load_keyword_returns_metrics(self) -> None:
        r = keyword_loader.load(_fixture("keyword_analysis.xlsx"))
        self.assertEqual(r.row_count, 3)
        for rec in r.records:
            self.assertIsInstance(rec, KeywordMetric)
            self.assertTrue(rec.keyword)
            self.assertIsInstance(rec.search_volume, Decimal)

    def test_keyword_dedup_key(self) -> None:
        rec = r = keyword_loader.load(_fixture("keyword_analysis.xlsx")).records[0]
        self.assertTrue(rec.dedup_key().startswith("kw:"))


class TestMarketLoader(unittest.TestCase):
    def test_load_market_returns_metrics(self) -> None:
        r = market_loader.load(_fixture("market_analysis.xlsx"))
        self.assertEqual(r.row_count, 2)
        for rec in r.records:
            self.assertIsInstance(rec, CategoryMetric)
            self.assertTrue(rec.category)


class TestCategoryLoader(unittest.TestCase):
    def test_load_category_returns_metrics(self) -> None:
        r = category_loader.load(_fixture("category_analysis.xlsx"))
        self.assertEqual(r.row_count, 2)
        for rec in r.records:
            self.assertIsInstance(rec, CategoryMetric)
            self.assertTrue(rec.category)


class TestBrandAnalyticsLoader(unittest.TestCase):
    def test_load_brand_analytics_returns_metrics(self) -> None:
        r = brand_analytics_loader.load(_fixture("brand_analytics.xlsx"))
        self.assertEqual(r.row_count, 3)
        for rec in r.records:
            self.assertIsInstance(rec, BrandMetric)
            self.assertTrue(rec.brand)
        # BA signature fields should be populated on at least one row.
        self.assertTrue(any(rec.click_share is not None for rec in r.records))
        self.assertTrue(any(rec.conversion_share is not None for rec in r.records))


class TestBrandLoader(unittest.TestCase):
    def test_load_brands_returns_metrics(self) -> None:
        r = brand_loader.load(_fixture("brands.xlsx"))
        self.assertEqual(r.row_count, 3)
        for rec in r.records:
            self.assertIsInstance(rec, BrandMetric)
            self.assertTrue(rec.brand)


class TestSellerLoader(unittest.TestCase):
    def test_load_sellers_returns_metrics(self) -> None:
        r = seller_loader.load(_fixture("sellers.xlsx"))
        self.assertEqual(r.row_count, 3)
        for rec in r.records:
            self.assertIsInstance(rec, SellerMetric)
            self.assertTrue(rec.seller)

    def test_seller_loader_uses_seller_field_not_buybox(self) -> None:
        # ``buybox_seller`` belongs on the product row, not here.
        r = seller_loader.load(_fixture("sellers.xlsx"))
        for rec in r.records:
            self.assertFalse(hasattr(rec, "buybox_seller"))


class TestNormalizedModels(unittest.TestCase):
    """Model-level invariants."""

    def test_source_info_defaults_to_imported_excel(self) -> None:
        s = SourceInfo()
        self.assertEqual(s.source_type, "imported_excel")
        self.assertTrue(s.source_hash)

    def test_source_info_invalid_type_falls_back(self) -> None:
        s = SourceInfo(source_type="not_allowed")
        self.assertEqual(s.source_type, "imported_excel")

    def test_amazon_product_dedup_key_uses_asin_when_present(self) -> None:
        p = AmazonProduct(asin="B0TEST001", source_row=2)
        self.assertEqual(p.dedup_key(), "asin:B0TEST001")

    def test_amazon_product_dedup_key_falls_back_to_brand_title(self) -> None:
        p = AmazonProduct(brand="ACME", title="Widget", source_row=2)
        self.assertEqual(p.dedup_key(), "bt:ACME|Widget")

    def test_amazon_product_dedup_key_handles_missing_fields(self) -> None:
        p = AmazonProduct(source_row=2)
        self.assertEqual(p.dedup_key(), "bt:?|?")

    def test_search_appearance_dedup_key_includes_rank(self) -> None:
        s = AmazonSearchAppearance(
            keyword="kw", asin="B0TEST001", search_rank=5, source_row=2
        )
        self.assertEqual(s.dedup_key(), "kw|B0TEST001|5")

    def test_keyword_metric_dedup_key(self) -> None:
        k = KeywordMetric(keyword="chicken saddle", source_row=2)
        self.assertEqual(k.dedup_key(), "kw:chicken saddle")

    def test_brand_metric_dedup_key(self) -> None:
        b = BrandMetric(brand="ACME", source_row=2)
        self.assertEqual(b.dedup_key(), "brand:ACME")

    def test_seller_metric_dedup_key(self) -> None:
        s = SellerMetric(seller="SellerOne", source_row=2)
        self.assertEqual(s.dedup_key(), "seller:SellerOne")

    def test_category_metric_dedup_key(self) -> None:
        c = CategoryMetric(category="Poultry", source_row=2)
        self.assertEqual(c.dedup_key(), "cat:Poultry")

    def test_amazon_product_to_dict_round_trip(self) -> None:
        p = AmazonProduct(asin="B0TEST001", title="X", price=Decimal("9.99"),
                          source_row=2, source_file="f.xlsx", source_sheet="s")
        d = p.to_dict()
        self.assertEqual(d["asin"], "B0TEST001")
        self.assertEqual(d["price"], "9.99")
        self.assertEqual(d["source_row"], 2)

    def test_search_appearance_to_dict_round_trip(self) -> None:
        s = AmazonSearchAppearance(keyword="kw", asin="B0TEST001", is_sponsored=True,
                                   source_row=2, source_file="f.xlsx")
        d = s.to_dict()
        self.assertEqual(d["keyword"], "kw")
        self.assertTrue(d["is_sponsored"])
        self.assertEqual(d["source_type"], "imported_excel")


class TestEndToEndDispatch(unittest.TestCase):
    """detect -> get_loader -> load pipeline."""

    def test_pipeline_for_each_fixture(self) -> None:
        cases = [
            ("products.xlsx", "products"),
            ("search.xlsx", "search"),
            ("keyword_analysis.xlsx", "keyword"),
            ("market_analysis.xlsx", "market"),
            ("category_analysis.xlsx", "category"),
            ("brand_analytics.xlsx", "brand_analytics"),
            ("brands.xlsx", "brands"),
            ("sellers.xlsx", "sellers"),
        ]
        for fname, expected_type in cases:
            with self.subTest(fixture=fname):
                fp = _fixture(fname)
                det = detect_workbook(fp)
                self.assertEqual(det.detected_type, expected_type,
                                 f"detection failed for {fname}")
                loader = get_loader(det.detected_type)
                self.assertIsNotNone(loader, f"no loader for {det.detected_type}")
                result = loader.load(fp)  # type: ignore[union-attr]
                self.assertGreater(result.row_count, 0,
                                   f"no rows loaded from {fname}")
                self.assertEqual(len(result.errors), 0,
                                 f"errors loading {fname}: {result.errors}")


if __name__ == "__main__":
    unittest.main()
